import axios from 'axios';

const BASE_URL = 'http://localhost:8080/api';
let passed = 0;
let failed = 0;

function assert(condition, name) {
  if (condition) {
    console.log(`✅ PASS: ${name}`);
    passed++;
  } else {
    console.error(`❌ FAIL: ${name}`);
    failed++;
  }
}

async function runTests() {
  console.log('\n======================================================');
  console.log('🧪 MULTI-DEVICE SPRING BOOT + MYSQL AUTH TEST SUITE');
  console.log('======================================================\n');

  // Test 1: Health Check
  console.log('--- 1. Backend Health Check ---');
  const healthRes = await axios.get(`${BASE_URL}/auth/health`);
  assert(healthRes.data.status === 'UP', 'Spring Boot backend is UP and running');

  // Test 2: Device 1: Registration
  console.log('\n--- 2. Device 1: User Registration in Database ---');
  const testMobile = `98${Math.floor(10000000 + Math.random() * 90000000)}`;
  const testPassword = 'SecurePassword@2026';
  
  const regPayload = {
    mobile: testMobile,
    username: 'Dr. Aaradhya Verma',
    password: testPassword,
    confirmPassword: testPassword,
    location: 'Indiranagar, Bengaluru, Karnataka',
    emergencyContactName: 'Kavita Verma (Spouse)',
    emergencyContactNumber: '+91 98765 43210',
    age: 36,
    gender: 'Female',
    bloodGroup: 'O+',
    allergies: 'Penicillin',
    existingConditions: 'Mild Asthma',
    currentMedications: 'Salbutamol Inhaler'
  };

  const regRes = await axios.post(`${BASE_URL}/auth/register`, regPayload);
  assert(regRes.data.success === true, 'Device 1 registration succeeded without OTP');
  assert(regRes.data.token && regRes.data.token.length > 20, 'JWT Token generated by backend');
  assert(regRes.data.user.mobile === testMobile, 'User mobile persisted correctly in database');
  assert(regRes.data.user.username === 'Dr. Aaradhya Verma', 'User username persisted correctly in database');
  assert(regRes.data.user.password === undefined, 'Password hash is NOT leaked in response DTO');

  // Test 3: Device 2: Login from another device with same credentials
  console.log('\n--- 3. Device 2: Login from Mobile / Another Device ---');
  const loginRes = await axios.post(`${BASE_URL}/auth/login`, {
    mobile: testMobile,
    password: testPassword
  });
  assert(loginRes.data.success === true, 'Device 2 login succeeded against database');
  assert(loginRes.data.user.id === regRes.data.user.id, 'Same user ID loaded on Device 2');
  assert(loginRes.data.user.bloodGroup === 'O+', 'Clinical snapshot (Blood Group O+) retrieved on Device 2');
  assert(loginRes.data.user.emergencyContactName === 'Kavita Verma (Spouse)', 'Emergency contact retrieved on Device 2');

  const device2Token = loginRes.data.token;

  // Test 4: Token Validation & Session Persistence (Refresh Simulation)
  console.log('\n--- 4. Browser Refresh / Session Verification (GET /api/auth/me) ---');
  const meRes = await axios.get(`${BASE_URL}/auth/me`, {
    headers: { Authorization: `Bearer ${device2Token}` }
  });
  assert(meRes.data.id === regRes.data.user.id, 'Session verified via JWT on refresh without creating new user');
  assert(meRes.data.username === 'Dr. Aaradhya Verma', 'User profile intact after browser refresh');

  // Test 5: Profile Update across devices
  console.log('\n--- 5. Profile Update (PUT /api/auth/profile) ---');
  const updateRes = await axios.put(`${BASE_URL}/auth/profile`, {
    username: 'Dr. Aaradhya Verma (MD)',
    location: 'Koramangala, Bengaluru',
    emergencyContactName: 'Kavita Verma',
    emergencyContactNumber: '9876543210',
    allergies: 'Penicillin, Dust',
    existingConditions: 'Controlled Asthma',
    currentMedications: 'Salbutamol (PRN)'
  }, {
    headers: { Authorization: `Bearer ${device2Token}` }
  });
  assert(updateRes.data.username === 'Dr. Aaradhya Verma (MD)', 'Profile updated in database');
  assert(updateRes.data.allergies === 'Penicillin, Dust', 'Updated allergies persisted in database');

  // Test 6: Zero-OTP Password Reset (Emergency Contact Verification)
  console.log('\n--- 6. Zero-OTP Password Reset (POST /api/auth/reset-password) ---');
  const newPassword = 'NewSecretPassword@2026';
  const resetRes = await axios.post(`${BASE_URL}/auth/reset-password`, {
    mobile: testMobile,
    emergencyContactNumber: '9876543210',
    newPassword: newPassword,
    confirmNewPassword: newPassword
  });
  assert(resetRes.data.success === true, 'Password reset succeeded via emergency contact verification');

  // Test login with new password
  const newLoginRes = await axios.post(`${BASE_URL}/auth/login`, {
    mobile: testMobile,
    password: newPassword
  });
  assert(newLoginRes.data.success === true, 'Login with new password succeeded');

  // Test 7: Error Handling - Duplicate Mobile Number
  console.log('\n--- 7. Error Handling: Duplicate Mobile Registration ---');
  try {
    await axios.post(`${BASE_URL}/auth/register`, regPayload);
    assert(false, 'Duplicate registration should fail');
  } catch (err) {
    assert(err.response?.status === 400, 'Duplicate registration rejected with 400 Bad Request');
    assert(err.response?.data?.error?.includes('already exists'), `Clear duplicate message: "${err.response?.data?.error}"`);
  }

  // Test 8: Error Handling - Invalid Credentials
  console.log('\n--- 8. Error Handling: Invalid Login Credentials ---');
  try {
    await axios.post(`${BASE_URL}/auth/login`, {
      mobile: testMobile,
      password: 'WrongPassword999'
    });
    assert(false, 'Invalid login should fail');
  } catch (err) {
    assert(err.response?.status === 401, 'Invalid password rejected with 401 Unauthorized');
    assert(err.response?.data?.error?.includes('Incorrect password'), `Clear invalid credential message: "${err.response?.data?.error}"`);
  }

  // Test 9: Error Handling - Short Password
  console.log('\n--- 9. Error Handling: Validation Rejection ---');
  try {
    await axios.post(`${BASE_URL}/auth/register`, {
      mobile: '9899999999',
      username: 'Short Pass User',
      password: '123',
      confirmPassword: '123',
      location: 'Bengaluru',
      emergencyContactName: 'Contact',
      emergencyContactNumber: '9876543210'
    });
    assert(false, 'Short password should fail');
  } catch (err) {
    assert(err.response?.status === 400, 'Short password rejected by Bean Validation');
  }

  // Test 10: Demo User Pre-seeded Login
  console.log('\n--- 10. Pre-seeded Demo Login (9876543210 / Password@123) ---');
  const demoLogin = await axios.post(`${BASE_URL}/auth/login`, {
    mobile: '9876543210',
    password: 'Password@123'
  });
  assert(demoLogin.data.success === true, 'Pre-seeded demo user (Aarav Sharma) logs in successfully');
  assert(demoLogin.data.user.username === 'Aarav Sharma', 'Demo user profile loaded');

  console.log('\n======================================================');
  console.log(`📊 TEST RESULTS: ${passed} PASSED, ${failed} FAILED`);
  console.log('======================================================\n');
}

runTests().catch(err => {
  console.error('Fatal test error:', err);
  process.exit(1);
});
